### ISSUE TITLE
使用NotifyOnCancel时出现coredump

### ISSUE THREAD

**Issue by geblue** [apache/brpc#1369]
coredump的具体位置在 `error_code ==0`的分支里`static_cast<google::protobuf::Closure*>(data)->Run();` 这句。有个疑问是 `ResetNonPods`里为什么一定要调用 `RunOnCancel`呢？如果之前已经满足了cancel的条件，`RunOnCancel` 以及`data` 代表的回调函数已经被调用过了，`data` 对应的closure已经被删除了吧, 这时候`ResetNonPods`再调用 `RunOnCancel`,是不是有问题？

**Comment by wwbmmm** [comment]
We close this issue because it is irreproducible and inactive for a long time.
If you can reproduce this issue with the latest version of bRPC, please reopen this issue and tell us how to reproduce.

**Comment by ivanallen** [comment]
似乎遇到了同样的问题：

```
(gdb) bt
--
#0  0x0000000000fe657b in brpc::Controller::RunOnCancel(bthread_id_t, void*, int) ()
#1  0x0000000000fc692b in bthread_id_error_verbose ()
#2  0x0000000000fed163 in brpc::Controller::ResetNonPods() ()
#3  0x0000000000fed2af in brpc::Controller::~Controller() ()
#4  0x0000000000fed4a1 in brpc::Controller::~Controller() ()
#5  0x000000000105314a in brpc::policy::HttpResponseSender::~HttpResponseSender() ()
#6  0x0000000001056d04 in brpc::policy::HttpResponseSenderAsDone::~HttpResponseSenderAsDone() ()
#7  0x00000000006327e0 in brpc::ClosureGuard::~ClosureGuard (this=<synthetic pointer>, __in_chrg=<optimized out>)
at include/brpc/closure_guard.h:39
#8  master::MessageQueueServiceImpl::consume (this=0x38ea9e0, controller=0x7fa758130730, request=<optimized out>, response=0x7fa71c0b8910, done=0x7fa71c0b8810)
at src/master/message_queue_service.cc:407
#9  0x0000000001054e7f in brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) ()
#10 0x0000000001010c37 in brpc::ProcessInputMessage(void*) ()
#11 0x0000000001011efe in brpc::InputMessenger::OnNewMessages(brpc::Socket*) ()
#12 0x00000000010e052d in brpc::Socket::ProcessEvent(void*) ()
#13 0x0000000000fd7ebf in bthread::TaskGroup::task_runner(long) ()
#14 0x0000000001164f41 in bthread_make_fcontext ()
#15 0x0000000000000000 in ?? ()

```

@wwbmmm

**Comment by chenBright** [comment]
Maybe #2557 has fixed this problem.
