### ISSUE TITLE
brpc初始化失败，cpu持续100%

### ISSUE THREAD

**Issue by jgli** [apache/brpc#2638]
**Describe the bug (描述bug)**
brpc服务初始化，cpu 100%卡住不动

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler: gcc-9.5.0/
brpc: release-1.7
protobuf: protobuf-3.14.0

**Additional context/screenshots (更多上下文/截图)**
![image](https://github.com/apache/brpc/assets/3295659/7809c3ca-4691-4ca7-beec-3bfa78e11df3)

**Comment by jgli** [comment]
OS: CentOS Linux release 7.6.1810 (Core), 3.10.0-1160.42.2.el7.x86_64

**Comment by yanglimingcn** [comment]
能发个栈信息吗？

**Comment by jgli** [comment]
(gdb) bt
#0  0x00002b9e6c746917 in sched_yield () from /lib64/libc.so.6
#1  0x00002b9e69c93efd in butil::internal::WaitForInstance(long*) () from /home/ops/attr_storage-el7-1.0.14/bin/../lib/libbrpc.so
#2  0x00002b9e69cbdae5 in butil::PlatformThread::SetName(char const*) () from /home/ops/attr_storage-el7-1.0.14/bin/../lib/libbrpc.so
#3  0x00002b9e69cea009 in bvar::detail::SamplerCollector::sampling_thread(void*) () from /home/ops/attr_storage-el7-1.0.14/bin/../lib/libbrpc.so
#4  0x00002b9e693b5ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00002b9e6c761b0d in clone () from /lib64/libc.so.6

**Comment by jgli** [comment]
![image](https://github.com/user-attachments/assets/cab5a5cd-ca40-4c71-84a3-318fb0dd40b8)
![image](https://github.com/user-attachments/assets/7d1e72ff-77d7-42f6-ac65-9908ac5efd79)
